export function getClass(state) { return state.charClass; }
export function getRace(state) { return state.race; }
export function getSkills(state) { return state.skills; }
export function getAbilityScores(state) { return state.abilityScores; }
export function getAllClasses(state) { return state.allClasses; }
export function getAllRaces(state) { return state.allRaces; }
export function getAllBackgrounds(state) { return state.allBackgrounds; }
export function getAllAlignments(state) { return state.allAlignments; }
export function getAllSkills(state) { return state.allSkills; }